# Generated by Django 5.2.8 on 2026-01-02 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_comment_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datetime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="created_at",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_created",
                to="auctions.datetime",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.datetime",
            ),
        ),
    ]
