# Generated by Django 5.2.8 on 2026-01-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_created_at_alter_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
