# Generated by Django 5.2.8 on 2026-01-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
