# Generated by Django 5.2.8 on 2026-01-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_bid_amount_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
