# Generated by Django 6.0.1 on 2026-01-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_bid_id_alter_category_id_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="item",
        ),
    ]
